version: "3.7"
services:
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - bulletinnet

  go-rest-gin-k8s:
    image: niels58/go-rest-gin-k8s:v1
    build:
      context: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      GET_HOST_FROM: dns
    networks:
      - bulletinnet
    volumes:
      - .:/go/src/go-rest-gin-k8s
    depends_on:
      - db
#      db:
#        condition: service_healthy
#    command: ["./wait-for-it.sh", "db:5432", "--", "echo", "hola"]
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  bulletinnet:
    driver: bridge
